# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Switch Kite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Switch Kite
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  pod 'HandyJSON', '~> 4.1.1'
  pod 'MJRefresh'
  pod 'Reusable'
  pod 'TagListView'
  pod 'KKPhotoBrowser'


end
